services:
  - type: web
    name: waste-management-system
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wms-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
      - key: NODE_VERSION
        value: 20.11.0
      - key: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
        sync: false

databases:
  - name: wms-db
    databaseName: waste_management
    user: wms_user
    plan: free
    region: singapore
